version: "3.8"

services:
  cloud-concierge:
    build: ./main/
    working_dir: /main/
    environment:
      - "CLOUDCONCIERGE_APIPATH=$CLOUDCONCIERGE_APIPath"
      - "CLOUDCONCIERGE_DIVISIONCLOUDCREDENTIALS=$CLOUDCONCIERGE_DivisionCloudCredentials"
      - "CLOUDCONCIERGE_INFRACOSTAPITOKEN=$CLOUDCONCIERGE_InfracostAPIToken"
      - "CLOUDCONCIERGE_JOBID=$CLOUDCONCIERGE_JobID"
      - "CLOUDCONCIERGE_ORGTOKEN=$CLOUDCONCIERGE_OrgToken"
      - "CLOUDCONCIERGE_MIGRATIONHISTORYSTORAGE=$CLOUDCONCIERGE_MigrationHistoryStorage"
      - "CLOUDCONCIERGE_PROVIDERS=$CLOUDCONCIERGE_Providers"
      - "CLOUDCONCIERGE_STATEBACKEND=$CLOUDCONCIERGE_StateBackend"
      - "CLOUDCONCIERGE_TERRAFORMCLOUDORGANIZATION=$CLOUDCONCIERGE_TerraformCloudOrganization"
      - "CLOUDCONCIERGE_TERRAFORMCLOUDTOKEN=$CLOUDCONCIERGE_TerraformCloudToken"
      - "CLOUDCONCIERGE_TERRAFORMVERSION=$CLOUDCONCIERGE_TerraformVersion"
      - "CLOUDCONCIERGE_VCSBASEBRANCH=$CLOUDCONCIERGE_VCSBaseBranch"
      - "CLOUDCONCIERGE_VCSSYSTEM=$CLOUDCONCIERGE_VCSSystem"
      - "CLOUDCONCIERGE_VCSREPO=$CLOUDCONCIERGE_VCSRepo"
      - "CLOUDCONCIERGE_VCSTOKEN=$CLOUDCONCIERGE_VCSToken"
      - "CLOUDCONCIERGE_VCSUSER=$CLOUDCONCIERGE_VCSUser"
      - "CLOUDCONCIERGE_PULLREVIEWERS=$CLOUDCONCIERGE_PullReviewers"
      - "CLOUDCONCIERGE_RESOURCESWHITELIST=$CLOUDCONCIERGE_ResourcesWhiteList"
      - "CLOUDCONCIERGE_WORKSPACEDIRECTORIES=$CLOUDCONCIERGE_WorkspaceDirectories"
    networks:
      - network
    volumes:
      - main:/main

networks:
  network:
    name: cloud-concierge
    driver: bridge

volumes:
  main:
    name: main
    driver: local
