name: cloud-concierge daily execution
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  cloud-concierge:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Run cloud-concierge
        uses: dragondropcloud/cloud-concierge:latest
        env:
          CLOUDCONCIERGE_DIVISIONCLOUDCREDENTIALS: ${{ secrets.CLOUDCONCIERGE_DIVISIONCLOUDCREDENTIALS }}
          CLOUDCONCIERGE_PROVIDERS: ${{ secrets.CLOUDCONCIERGE_PROVIDERS }}
          CLOUDCONCIERGE_TERRAFORMVERSION: ${{ secrets.CLOUDCONCIERGE_TERRAFORMVERSION }}
          CLOUDCONCIERGE_WORKSPACEDIRECTORIES: ${{ secrets.CLOUDCONCIERGE_WORKSPACEDIRECTORIES }}
          CLOUDCONCIERGE_RESOURCEWHITELIST: ${{ secrets.CLOUDCONCIERGE_RESOURCEWHITELIST }}
          CLOUDCONCIERGE_STATEBACKEND: ${{ secrets.CLOUDCONCIERGE_STATEBACKEND }}
          CLOUDCONCIERGE_VCSTOKEN: ${{ secrets.CLOUDCONCIERGE_VCSTOKEN }}
          CLOUDCONCIERGE_VCSUSER: ${{ secrets.CLOUDCONCIERGE_VCSUSER }}
          CLOUDCONCIERGE_VCSREPO: ${{ secrets.CLOUDCONCIERGE_VCSREPO }}
          CLOUDCONCIERGE_VCSSYSTEM: ${{ secrets.CLOUDCONCIERGE_VCSSYSTEM }}
          CLOUDCONCIERGE_VCSBASEBRANCH: ${{ secrets.CLOUDCONCIERGE_VCSBASEBRANCH }}
          CLOUDCONCIERGE_PULLREVIEWERS: ${{ secrets.CLOUDCONCIERGE_PULLREVIEWERS }}
          CLOUDCONCIERGE_INFRACOSTAPITOKEN: ${{ secrets.CLOUDCONCIERGE_INFRACOSTAPITOKEN }}
          CLOUDCONCIERGE_ORGTOKEN: ${{ secrets.CLOUDCONCIERGE_ORGTOKEN }}
