name: continuous deployment (CD)
on:
  push:
    tags:
      - v*.*.*
      - v*.*.*-beta

jobs:
  cloud-concierge-to-dockerhub:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Log-in to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Dev release and image deployment to DockerHub
      - name: Checkout branch - dev
        uses: actions/checkout@v3
        if: ${{ contains(github.ref_name, '-beta' ) }}
        ref: dev

      - name: Release version dev
        if: ${{ contains(github.ref_name, '-beta' ) }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{ github.ref_name }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true

      - name: Build and push Docker image dev
        if: ${{ contains(github.ref_name, '-beta' ) }}
        uses: docker/build-push-action@v3
        with:
          context: main/.
          push: true
          tags: |
            dragondropcloud/cloud-concierge-dev:latest
            dragondropcloud/cloud-concierge-dev:${{ github.ref_name }}

      # Prod release and image deployment to DockerHub
      - name: Checkout branch - prod
        uses: actions/checkout@v3
        if: ${{ !contains(github.ref_name, '-beta' ) }}
        ref: prod

      - name: Release version prod
        if: ${{ !contains(github.ref_name, '-beta' ) }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: ${{ github.ref_name }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

      - name: Build and push Docker image prod
        if: ${{ !contains(github.ref_name, '-beta' ) }}
        uses: docker/build-push-action@v3
        with:
          context: main/.
          push: true
          tags: |
            dragondropcloud/cloud-concierge:latest
            dragondropcloud/cloud-concierge:${{ github.ref_name }}
